# .github/workflows/create-release-branch-v1.yml
name: Create Feature Branches in Repos v1

on:
  # This workflow can be run manually from the Actions tab.
  workflow_dispatch:
    inputs:
      DRY_RUN:
        description: 'Run without pushing any changes. Set to false to apply changes.'
        required: true
        type: boolean
        default: true
      BRANCH_NAME:
        description: 'The name of the new feature/release branch to create (e.g., 24.1-fr1).'
        required: true
        type: string
      NEW_VERSION:
        description: 'The new version to set in the Makefile on the main/source branch (e.g., 25.0).'
        required: true
        type: string
      SOURCE_BRANCH:
        description: 'The branch to create the new branch from.'
        required: false
        type: string
        default: 'main'
      TRIGGER_BRANCH:
        description: 'The branch that must exist in a repo for it to be processed.'
        required: false
        type: string
        default: 'olive'
      VERSION_VARIABLE:
        description: 'The name of the version variable in the Makefile.'
        required: false
        type: string
        default: 'VERSION'
      BRANCH_VARIABLE:
        description: 'The name of the branch variable in the Makefile.'
        required: false
        type: string
        default: 'BRANCH'
      OPENSTACK_K8S_TAG_VARIABLE:
        description: 'The name of the OpenStack K8s tag variable in the Makefile (for install_yamls).'
        required: false
        type: string
        default: 'OPENSTACK_K8S_TAG'

jobs:
  create-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token from the GitHub App
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          echo "yq version $(yq --version) installed."
          
      - name: Checkout code (for the workflow itself)
        uses: actions/checkout@v4

      - name: Create Branches and Update Version
        env:
          # Use the token generated from the GitHub App
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          # Use current org as the ORG_NAME
          ORG_NAME: ${{ github.repository_owner }}
          # --- CONFIGURATION FROM INPUTS ---
          BRANCH_NAME: ${{ inputs.BRANCH_NAME }}
          NEW_VERSION: ${{ inputs.NEW_VERSION }}
          VERSION_VARIABLE: ${{ inputs.VERSION_VARIABLE }}
          BRANCH_VARIABLE: ${{ inputs.BRANCH_VARIABLE }}
          OPENSTACK_K8S_TAG_VARIABLE: ${{ inputs.OPENSTACK_K8S_TAG_VARIABLE }}
          TRIGGER_BRANCH: ${{ inputs.TRIGGER_BRANCH }}
          SOURCE_BRANCH: ${{ inputs.SOURCE_BRANCH }}
          DRY_RUN: ${{ inputs.DRY_RUN }}
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.

          # Validate that required variables are set
          # Note: GitHub UI enforces required inputs, but this is a good safeguard.
          if [[ -z "$BRANCH_NAME" ]] || [[ -z "$NEW_VERSION" ]]; then
            echo "Error: Required inputs BRANCH_NAME or NEW_VERSION were not provided."
            exit 1
          fi

          if [ "$DRY_RUN" = "true" ]; then
            echo "!!! --- Running in DRY RUN mode. No changes will be pushed. --- !!!"
          fi
          
          echo "Running with the following configuration:"
          echo "Organization: ${ORG_NAME}"
          echo "Feature Branch Name: ${BRANCH_NAME}"
          echo "New Version on main: ${NEW_VERSION}"
          echo "Trigger Branch: ${TRIGGER_BRANCH}"
          echo "Source Branch: ${SOURCE_BRANCH}"
          echo "-------------------------------------------"
          
          echo "Searching for repositories in organization '${ORG_NAME}'..."
          repos=$(gh repo list $ORG_NAME --limit 1000 --json name --jq '.[] | .name')

          if [ -z "$repos" ]; then
            echo "No repositories found in the organization or permissions are missing."
            exit 1
          fi

          created_repos=""

          for repo_name in $repos; do
            echo "--- Checking repository: ${repo_name} ---"

            # for now skip rabbitmq-cluster-operator
            if [[ "$repo_name" == "rabbitmq-cluster-operator" ]]; then 
              continue
            fi

            # Check if the trigger branch exists by checking the exit code of the API call.
            if gh api "repos/${ORG_NAME}/${repo_name}/branches/${TRIGGER_BRANCH}" >/dev/null 2>&1; then
              echo "✅ Trigger branch '${TRIGGER_BRANCH}' found in ${repo_name}."

              TEMP_DIR=$(mktemp -d)
              echo "Cloning repository into ${TEMP_DIR}..."
              git clone "https://x-access-token:${GH_TOKEN}@github.com/${ORG_NAME}/${repo_name}.git" "$TEMP_DIR"
              
              cd "$TEMP_DIR"

              if ! git show-ref --verify --quiet "refs/remotes/origin/${SOURCE_BRANCH}"; then
                echo "⚠️ Source branch '${SOURCE_BRANCH}' does not exist in ${repo_name}. Skipping."
                cd ..
                rm -rf "$TEMP_DIR"
                continue
              fi

              # Skip the entire repository if the new branch already exists.
              if git show-ref --verify --quiet "refs/remotes/origin/${BRANCH_NAME}"; then
                echo "ℹ️ Branch '${BRANCH_NAME}' already exists in ${repo_name}. Skipping this repository."
                cd ..
                rm -rf "$TEMP_DIR"
                continue
              fi
              
              # --- LOGIC: CREATE AND UPDATE THE NEW BRANCH ---
              echo "Creating branch '${BRANCH_NAME}' from '${SOURCE_BRANCH}'..."
              git checkout ${SOURCE_BRANCH}
              git checkout -b ${BRANCH_NAME}

              if [ -f "Makefile" ]; then
                echo "Makefile found. Checking for variables to update on new branch..."

                # ALL repos - Update the BRANCH variable
                if grep -qE "^${BRANCH_VARIABLE}\s*(\?=|=)" Makefile; then
                  sed -i -E "s/^(${BRANCH_VARIABLE}\s*(\?=|=)\s*).*/\1${BRANCH_NAME}/" Makefile
                fi

                # install_yamls - Update the OPENSTACK_K8S_TAG variable
                if [[ "$repo_name" == "install_yamls" ]]; then
                  if grep -qE "^${OPENSTACK_K8S_TAG_VARIABLE}\s*(\?=|=)" Makefile; then
                    sed -i -E "s/^((${OPENSTACK_K8S_TAG_VARIABLE})\s*(\?=|=)\s*).*/\1${BRANCH_NAME}-latest/" Makefile
                  fi
                fi
                  
                # Commit the changes only if a modification was made
                if ! git diff --quiet Makefile; then
                  echo "Showing changes for new branch '${BRANCH_NAME}':"
                  git diff                
                  if [ "$DRY_RUN" = "true" ]; then
                    echo "DRY RUN: Changes not committed."
                  else
                    git config --global user.name "github-actions[bot]"
                    git config --global user.email "github-actions[bot]@users.noreply.github.com"
                    git add Makefile
                    git commit -m "[${BRANCH_NAME}] Update Makefile for ${BRANCH_NAME}"
                    echo "Commit for version update created."
                  fi
                else
                  echo "No updates in the Makefile. No commit will be created for this branch."
                fi
              else
                  echo "No Makefile found. No changes will be committed to new branch."
              fi

              # Push the new branch with the potential new commit
              if [ "$DRY_RUN" = "true" ]; then
                echo "DRY RUN: Would push branch '${BRANCH_NAME}'."
              else
                git push origin ${BRANCH_NAME}
                echo "Branch successfully pushed."
              fi
              created_repos+="- ${repo_name}\n"

              # --- LOGIC: UPDATE SOURCE BRANCH AFTERWARDS ---
              if [[ "$repo_name" == "openstack-operator" ]]; then
                # Reset any uncommitted changes before switching branch.
                # In non-dry-run, this does nothing as changes were committed.
                # In dry-run, this discards the generated diff.
                git reset --hard              
                git checkout ${SOURCE_BRANCH}
                # Ensure we have the latest version of the source branch before making changes
                git pull origin ${SOURCE_BRANCH}

                if [ -f "Makefile" ]; then
                  # Construct the full version string by appending ".0"
                  FULL_MAKEFILE_VERSION="${NEW_VERSION}.0"

                  # Conditionally update the main VERSION variable on the source branch
                  if grep -qE "^${VERSION_VARIABLE}\s*(:=|\?=|=)" Makefile; then
                    sed -i -E "s/^(${VERSION_VARIABLE}\s*(:=|\?=|=)).*/\1 ${FULL_MAKEFILE_VERSION}/" Makefile

                    # Commit and push the change to the source branch
                    if ! git diff --quiet Makefile; then
                      echo "Showing changes for source branch '${SOURCE_BRANCH}':"
                      git diff
                      if [ "$DRY_RUN" = "true" ]; then
                        echo "DRY RUN: Changes not committed or pushed."
                      else
                        git config --global user.name "github-actions[bot]"
                        git config --global user.email "github-actions[bot]@users.noreply.github.com"
                        git add Makefile
                        git commit -m "Bump version to ${NEW_VERSION}"
                        echo "Pushing version update to ${SOURCE_BRANCH}..."
                        git push origin ${SOURCE_BRANCH}
                      fi
                    else
                      echo "Version in Makefile already up to date. No changes pushed to ${SOURCE_BRANCH}."
                    fi                      
                  else
                    echo "Variable '${VERSION_VARIABLE}' not found. No changes pushed to ${SOURCE_BRANCH}."
                  fi
                else
                  echo "No Makefile found. No changes pushed to ${SOURCE_BRANCH}."
                fi
              fi
              
              # Clean up
              cd ..
              rm -rf "$TEMP_DIR"

            else
              echo "❌ Trigger branch '${TRIGGER_BRANCH}' not found in ${repo_name}. Skipping."
            fi
          done

          echo "-------------------------------------------"
          if [ "$DRY_RUN" = "true" ]; then
            echo "Summary of repos where the new branch ${BRANCH_NAME} would have been created (DRY RUN):"
          else
            echo "Summary of repos where the new branch ${BRANCH_NAME} was created:"
          fi

          if [[ -n "$created_repos" ]]; then
            echo -e "$created_repos"
          else
            echo "No new branches were created."
          fi

      - name: Update openstack-k8s-operators-ci force-bump-branches.yaml and release-branch-sync.yaml workflows
        env:
          # Use the token generated from the GitHub App
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          # Use current org as the ORG_NAME
          ORG_NAME: ${{ github.repository_owner }}
          # --- CONFIGURATION FROM INPUTS ---
          BRANCH_NAME: ${{ inputs.BRANCH_NAME }}        
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.

          TEMP_DIR=$(mktemp -d)
          echo "Cloning repository into ${TEMP_DIR}..."
          git clone "https://x-access-token:${GH_TOKEN}@github.com/${ORG_NAME}/openstack-k8s-operators-ci.git" "$TEMP_DIR"
              
          cd "$TEMP_DIR"

          # --- LOGIC: UPDATE openstack-k8s-operators-ci force-bump-branches.yaml and release-branch-sync.yaml workflows ---
          RELEASE_BRANCH_SYNC_FILE=".github/workflows/release-branch-sync.yaml"
          if [ ! -f "${RELEASE_BRANCH_SYNC_FILE}" ]; then
            TARGET_PATH=".on.workflow_call.inputs.source_branch.default"

            # First, check if the path exists in the YAML file.
            # The '-e' (exit-status) flag causes yq to exit with a non-zero status
            # if the expression evaluates to false, null, or empty.
            if yq -e "has(${TARGET_PATH})" "${RELEASE_BRANCH_SYNC_FILE}" >/dev/null; then
              # Path exists, get the current value.
              CURRENT_VALUE=$(yq e "${TARGET_PATH}" "${RELEASE_BRANCH_SYNC_FILE}")

              echo "Path '$TARGET_PATH' found. Updating default from '${CURRENT_VALUE}' to '${BRANCH_NAME}'..."

              # Use yq to update the value in-place since the path is confirmed to exist.
              # The '-i' flag tells yq to modify the file directly.
              yq -i "${TARGET_PATH} = \"${BRANCH_NAME}\"" "${RELEASE_BRANCH_SYNC_FILE}"
            else
              echo "Path '$TARGET_PATH' not found in '${RELEASE_BRANCH_SYNC_FILE}'. No changes made."
            fi
          fi

          FORCE_BUMP_BRANCHES_FILE=".github/workflows/force-bump-branches.yaml"
          if [ ! -f "${FORCE_BUMP_BRANCHES_FILE}" ]; then
            TARGET_PATH=".jobs.trigger-jobs.strategy.matrix.branch"

            # First, check if the path exists in the YAML file.
            # The '-e' (exit-status) flag causes yq to exit with a non-zero status
            # if the expression evaluates to false, null, or empty.
            if yq -e "has(${TARGET_PATH})" "${FORCE_BUMP_BRANCHES_FILE}" >/dev/null; then
              # Path exists, get the current value.
              CURRENT_VALUE=$(yq e "${TARGET_PATH}" "${FORCE_BUMP_BRANCHES_FILE}")

              echo "Path '$TARGET_PATH' found. Updating default from '${CURRENT_VALUE}' to '${BRANCH_NAME}'..."

              # Use yq to update the value in-place since the path is confirmed to exist.
              # The '-i' flag tells yq to modify the file directly.
              yq -i "${TARGET_PATH} = \"${BRANCH_NAME}\"" "${FORCE_BUMP_BRANCHES_FILE}"
            else
              echo "Path '$TARGET_PATH' not found in '${FORCE_BUMP_BRANCHES_FILE}'. No changes made."
            fi
          fi

          # Commit the changes only if a modification was made
          if ! git diff --quiet ${RELEASE_BRANCH_SYNC_FILE} ${FORCE_BUMP_BRANCHES_FILE}; then
            echo "Showing changes for new branch '${BRANCH_NAME}':"
            git diff                
            if [ "$DRY_RUN" = "true" ]; then
              echo "DRY RUN: Changes not committed."
            else
              git config --global user.name "github-actions[bot]"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              git add ${WORKFLOW_FILE}
              git commit -m "[${BRANCH_NAME}] Update ${WORKFLOW_FILE} for ${BRANCH_NAME}"
              echo "Commit for version update created."
            fi
          else
            echo "No updates in the ${WORKFLOW_FILE}. No commit will be created for this branch."
          fi
          
          echo "Workflow finished."      
